import os
import json
import re
import math
from groq import Groq
from dotenv import load_dotenv



def _get_groq_client():
    """Initialize and return a Groq client using GROQ_API_KEY from .env."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise ValueError(
            "GROQ_API_KEY not set. Add it to a .env file in the project root."
        )
    return Groq(api_key=api_key)


def llm_signal(text: str) -> float:
    client = _get_groq_client()
    prompt = f"""You are an expert at distinguishing human-written text from AI-generated text.

    Analyze the following text and assess whether it was written by a human or generated by an AI.

    Consider:
    - Semantic coherence and idea progression
    - Stylistic consistency and tonal variation
    - Naturalness of phrasing and word choice
    - Common AI signatures such as em dashes or words like "genuinely"
    - Grammatical correctness and capitalization

    Return ONLY a JSON object in this exact format, nothing else:
    {{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

    Where 0.0 = certainly human, 1.0 = certainly AI.

    Text to analyze:
    \"\"\"
    {text}
    \"\"\"
    """

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, ValueError):
        return 0.5
    
    
def stylometric_signal(text: str) -> float | None:
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return None

    words = text.split()
    total_words = len(words)
    if total_words == 0:
        return None

    # Sub-metric 1: sentence length variance
    sentence_lengths = [len(s.split()) for s in sentences]
    mean_len = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    stddev = math.sqrt(variance)
    variance_score = max(0.0, 1.0 - (stddev / 10.0))

    # Sub-metric 2: punctuation variety
    punct_types = len(set(c for c in text if c in '",;:—…()!?'))
    punct_score = max(0.0, 1.0 - (punct_types / 6.0))

    # Sub-metric 3: average sentence complexity
    avg_words = total_words / len(sentences)
    complexity_score = max(0.0, min(1.0, (avg_words - 8) / 15.0))

    stylometric_score = (variance_score + punct_score + complexity_score) / 3.0
    return round(max(0.0, min(1.0, stylometric_score)), 4)
    

def confidence_score(llm_score: float, stylometric_score: float = None) -> dict:
    # if only one signal available, use it directly
    if stylometric_score is None:
        combined = llm_score
    else:
        # weighted average: 70% LLM, 30% stylometric
        combined = (llm_score * 0.70) + (stylometric_score * 0.30)

        # disagreement penalty: if signals differ by > 0.30, pull toward 0.5
        disagreement = abs(llm_score - stylometric_score)
        if disagreement > 0.45:
            pull = (disagreement - 0.30) * 0.5
            if combined > 0.5:
                combined = combined - pull
            else:
                combined = combined + pull

    combined = round(max(0.0, min(1.0, combined)), 4)

    # thresholds from planning.md
    if combined >= 0.70:
        attribution = "ai"
    elif combined <= 0.30:
        attribution = "human"
    else:
        attribution = "uncertain"

    return {
        "score": combined,
        "attribution": attribution,
    }

def generate_label(attribution: str, confidence_score: float) -> str:
    if attribution == "ai":
        return (
            "Our tools indicate this content was likely AI-generated. "
            "Our signals suggest AI authorship with high confidence. "
            "If you created this content yourself, you can submit an appeal and a reviewer will examine your submission."
        )
    elif attribution == "human":
        return (
            "Our tools indicate this content was likely written by a human. "
            "Our signals suggest human authorship with high confidence."
        )
    else:
        return (
            "We're not sure. Our tools found some patterns that sometimes appear in AI-generated writing, "
            "but not enough to reach a confident conclusion. "
            "This content has been marked as uncertain. "
            "If you created this content yourself, you can submit an appeal and a reviewer will examine your submission."
        )
    

    